### ISSUE TITLE
Recommend: electron-toolkit/utils supports setting auto launch

### ISSUE THREAD

**Issue by alex8088** [ElitoGame/RadialHexUI#12]
```
import { electronApp } from '@electron-toolkit/utils'

const success = electronApp.setAutoLaunch(true)
````

See [docs](https://github.com/alex8088/electron-toolkit/tree/master/packages/utils)

`setAutoLaunch` is implemented based on electron's API

**Comment by ElitoGame** [comment]
Thanks for the info didn't read into those docs yet. By any chance, do you know where the recommended folder for static assets like the app icon is (and how to import that asset in code afterwards)? I was having troubles adding an icon to the tray menu and showing it both in build and dev.

**Comment by alex8088** [comment]
For apps, you can create a folder in the root directory to put public resource files, so that out bundles don't have path matching problems. For renderers, you can create a foder called `public` in src/renderer.， `electron-vite` will automatically resolve.

**Comment by ElitoGame** [comment]
Hey, I tried out your suggestions and the assets are now showing great, thanks!
However, the Autolaunch is not working correctly yet. I only see this electron splash screen:
![Screenshot_1133](https://user-images.githubusercontent.com/43675593/193407106-a41e3531-8716-4b80-9a44-50ff1fbd4695.png)
Do you have any clue on how to solve this? Thanks in advance, your tools do help me speed up my work here quite a bit =)

**Comment by alex8088** [comment]
@ElitoGame This is normal, because `setautolaunch` will set the path of the currently running app as the startup path. During development, the startup path is the Electron executable  under `node_module`. However, after packaging, the startup path is the program execution path.

**Comment by alex8088** [comment]
You can determine whether to set auto launch via `is.dev` ( or `app.isPackaged`)

**Comment by ElitoGame** [comment]
Ahh, great, now I understand this better, thanks for all that help, appreciate it =)
