### ISSUE TITLE
Rough basis of Settings mechanics

### ISSUE THREAD

**Issue by s2110238051** [ElitoGame/RadialHexUI#18]
### Description:
- [x] Implement saving data to disk
- [x]  element grouping based on prototype

### TimeFrame:
GanttStart: 2022-11-02
GanttDue: 2022-11-13

**Comment by ElitoGame** [comment]
I have partially implemented saving data to disk already, as it was necessary for the Autolaunching and helpful to implement the Hex grid layout with interactions. Still got some local changes regarding that, as I haven't linked the backend (main) to the frontend (renderer) yet. Will be pushed as soon as I can launch Apps from a String saved in the settings.json file.
